### ISSUE TITLE
Parallel builds webhook

### ISSUE THREAD

**Issue by sanjioh** [coveralls-clients/coveralls-python#212]
Hi,

as per Coveralls docs:

https://docs.coveralls.io/parallel-build-webhook

a webhook needs to be called when parallel builds are done with reporting, to inform the service that no more submissions will be performed and thus it can start processing/displaying coverage data.

Is this something that `coveralls-python` can do? I'm running my CI on GitHub Actions and I'm not able to invoke the webhook without implementing a custom solution.

Thanks!

**Comment by agronholm** [comment]
Is this not sufficient for your use case? https://github.com/marketplace/actions/coveralls-github-action

**Comment by ArturKlauser** [comment]
There is PR #216  in the works that seems to address this issue.

**Comment by agronholm** [comment]
Yes, I managed to get it working in my own project using the code from that PR: https://github.com/agronholm/smtpproto/tree/master/.github/workflows

**Comment by sanjioh** [comment]
Hi,

thanks everybody for your replies.

I haven't tried it yet but, looking at the diff, #216 should work my end as well.

Nevertheless, in my opinion it would be nice to have a dedicated CLI argument in `coveralls-python` to explicitly tell Coveralls a parallel build has finished. This would make this tool independent from Coveralls' own GitHub Action, which would otherwise be required even after the merge of #216.

Maybe the `build_num` value (ref. https://docs.coveralls.io/parallel-build-webhook) could be left out, as CLI parameter to be provided by the user in accordance to their CI environment?

Thanks

**Comment by TheKevJames** [comment]
@sanjioh I've just merged #216 and am planning a release pending fixing some test issues (mostly Python/PyPy versions that got deprecated while my back was turned) in #218.

I might consider accepting a PR for adding a flag for this, but I just want to get up-to-speed on this issue first (I don't use Github Actions myself) and only so long as its not easily solve-able outside this project.

@agronholm 's suggestion seems to work pretty well -- looks like you could also do this in curl? Am I understanding correctly that adding the following line to your Github Actions workflow would also do the trick?
```yaml
- name: Tell Coveralls that the parallel build is finished
  run: |
    curl -k \
        https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN \
        -d "payload[build_num]=$GITHUB_SHA&payload[status]=done"
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
```

Looks like the `payload[build_num]` might be non-trivial to send with the whole `{SHA}-PR-{REF}` thing it has going on... maybe by adding my library to the mix? Would it work correctly by running:
```yaml
- name: Tell Coveralls that the parallel build is finished
  run: |
    BUILD_NUM=$(python -c 'import coveralls; print(coveralls.Coveralls.load_config_from_github()[1])')
    curl -k \
        https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN \
        -d "payload[build_num]=$BUILD_NUM&payload[status]=done"
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
```
