### ISSUE TITLE
[GitHub actions] KeyError: 'service_job_id'

### ISSUE THREAD

**Issue by escaped** [coveralls-clients/coveralls-python#247]
Hey,

thanks for this very useful client. I use it in almost all of my open source projects, but it recently stopped working. At first, I thought it was related to the new `2.2.0` release, but since I ran an older (previously successful) pipeline using `2.1.2` again and it failed, I think the issue lies somewhere else.

I use GitHub actions and integrated it like this ([full workflow](https://github.com/escaped/networkx-astar-path/blob/95766bb3845629363872494ff10a51e22b8ca1ab/.github/workflows/test.yml)):
```yaml
...
test:
      ....
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions coveralls  # or coveralls==2.1.2
      ...
      - name: coveralls
        run: coveralls  # or `coveralls debug` for debugging
        env:
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
  coveralls:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coveralls
      - name: coveralls
        run: coveralls --finish  # or `coveralls debug --finish` for debugging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

When running the pipeline, this is the error I am getting:

![image](https://user-images.githubusercontent.com/318650/101292056-fabf7800-37c1-11eb-9b5d-33d69f30a26c.png)

To debug this, I created a new [branch](https://github.com/escaped/networkx-astar-path/pull/4) based on a failing branch:
- [Initial run **failed**, version `2.2.0`](https://github.com/escaped/networkx-astar-path/pull/4/checks?check_run_id=1507482203)
- [Using `coverall debug` made the pipeline **pass**, version `2.2.0`](https://github.com/escaped/networkx-astar-path/runs/1507487604)
- [Reverting the commit and the pipeline **fails** again, version `2.2.0`](https://github.com/escaped/networkx-astar-path/pull/4/checks?check_run_id=1507493454)
- [Switching to version `2.1.2` **fails** the pipeline as well](https://github.com/escaped/networkx-astar-path/pull/4/checks?check_run_id=1507499152)
- [Using `coveralls debug` with version `2.1.2` **works** again](https://github.com/escaped/networkx-astar-path/pull/4/checks?check_run_id=1507506515)

I am a bit lost now; looks like it working fine when using the `debug` mode, but doesn't without it. Does anybody have an idea if that's a bug or a configuration issue on my side?
